num_1=(2)
num_2=(10)
sum_of_nummbers=(num_1+num_2)
sum_of_numbers2=(num_1-num_2)
sum_of_number3=(num_1*num_2)
sum_of_number4=(num_1/num_2)

name=("gio")
name=("nika")
name=("saba")
name=("goga")
name=("sandro")
print(name)

number=(2)
Number=(5)
nUmber=(6)
nuMber=(1)
numBer=(8)
print(number)
print(Number)
print(nUmber)
print(nuMber)
print(numBer)

number_1=("car")
number_2=("house")
number_3=("pool")
number_4=("bike")
number_5=("road")
print(number_1+number_2+number_3+number_4+number_5)
# სტრინგების შეერთებას კონკატენაცია ეწოდება

numb1=("gio")
numb2=(10)
print(numb1*numb2)

print(numb1-numb2)